### ISSUE TITLE
doesn't view full story pre-edit

### ISSUE THREAD

**Issue by Carol217** [csmithsalzberg/Mr-CSS-Rockets#2]
When viewing story pre-edit, we only see last edit.

Also it takes forever to load full story POST-edit.
When viewing posts, we see a table. Is that necessary? It ends up cluttering the page and causing lag.

Otherwise, looking great!

Sincerely and with best regards,
RoomOfOnesOwn...ToCode

**Comment by csmithsalzberg** [comment]
It isn't supposed to view the full story pre-edit. As for the table, we thought it was a cool addition. Yes, it does take a long time to load, and we think this is because many pre-loaded stories are held in the database. 

Thanks!

-Mr CSS Rockets
